name: Build Builder Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build
      run: |
        docker build -t ghcr.io/exhumer/builder-user:latest .

    - name: Push
      run: |
        docker push ghcr.io/exhumer/builder-user:latest
